# Generated by Django 2.1.4 on 2018-12-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opioid_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opioids',
            name='rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
