# Generated by Django 2.1.4 on 2018-12-18 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opioid_api', '0002_opioids_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opioids',
            name='rank',
        ),
    ]
